### ISSUE TITLE
Todo 

### ISSUE THREAD

**Issue by sweatpotato13** [sweatpotato13/some_project#13]
## 🚀 Proposal Detail

- [x] Search button Image
- [x] 주소창 주소 입력시 해당 위치로 카메라 변경 및 마커 설정
- [x] 마커 설정시 추가 정보 창

**Comment by 201411108** [comment]
TODO item #2 solved in branch feature/searchFunc, it needed PR

**Comment by 201411108** [comment]
All issues closed
