### ISSUE TITLE
Todo (20200102)

### ISSUE THREAD

**Issue by 201411108** [sweatpotato13/some_project#19]
## 🚀 Proposal Detail

* 한동
- [ ] multiple marker 기능
   - [ ] marker 저장하는 상태 관리
   - [ ] 새로 생성되는 마커에 서로 다른 색 입히기
   - [x] 추가, 제거 기능 구현(렌더링)
* 초롱
- [x] 찾은 무게 중심을 화면에 표시하는 기능 구현
   - [x] 추가한 마커의 중점을 찾아서 지도에 표현

**Comment by 201411108** [comment]
필요하면 TODO 내용 추가할 것
